### ISSUE TITLE
關於dlsite title reformat能增加幾個功能嗎?

### ISSUE THREAD

**Issue by JJININDER** [x94fujo6rpg/SomeTampermonkeyScripts#1]
您好，您的dlsite title reformat很好用，
請問標籤能像mangaoh一樣多個擷取社團名和日期的功能嗎?
難得遇到這麼實用的功能。

**Comment by x94fujo6rpg** [comment]
可以弄
但這樣組合會更多
一直加按鈕好像也不是辦法
可能要再弄個設定讓使用者自訂要甚麼格式

會先弄個版本是
[社團名稱] [dlsiteID] [日期] [標題]

**Comment by x94fujo6rpg** [comment]
新版已上線
![](https://i.imgur.com/CEhDo9A.png)
