### ISSUE TITLE
ehx_direct_download doesn't work after they change search engine.

### ISSUE THREAD

**Issue by scor2** [x94fujo6rpg/SomeTampermonkeyScripts#4]
3 days ago, they changed search engine.

and many script doesn't work include ehx_direct_download

**Comment by scor2** [comment]
미안해. 당신의 스크립트는 잘 작동해.

**Comment by x94fujo6rpg** [comment]
If you are using Tampermonkey, it might be the problem after the recent update of the extension.
The script does not load regularly and needs to be refresh the page several times.
https://github.com/Tampermonkey/tampermonkey/issues/1617
